"""Add tenant_crm_workspaces table

Revision ID: 0023
Revises: 0022
Create Date: 2026-04-26 18:20:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0023'
down_revision = '0022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_crm_workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=False),
    sa.Column('user_slots', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crm_workspaces_tenant_id', 'tenant_crm_workspaces', ['tenant_id'], unique=False)
    op.create_index('ix_crm_workspaces_workspace_id', 'tenant_crm_workspaces', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crm_workspaces_workspace_id', table_name='tenant_crm_workspaces')
    op.drop_index('ix_crm_workspaces_tenant_id', table_name='tenant_crm_workspaces')
    op.drop_table('tenant_crm_workspaces')
    # ### end Alembic commands ###
